clouway-incubator/bank-with-angularjs

.gitignore
pom.xml
src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/Jetty.java
src/test/java/com/clouway/bank/SampleTest.java

Added a sample java app which uses Jetty to serve the static content in the static folder.

bank: initial java project skeleton

---

frontend/.gitignore
frontend/package.json

Added a package.json for the npm to mark initial project folder structure.

admin/frontend: add initial npm package

---

src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/Jetty.java
src/main/java/com/clouway/bank/MainPage.java
src/main/resources/com/clouway/bank/MainPage.html

MainPage.html served with sitebricks. Created for the skeleton.
Fixes #3

bank: serve main page using sitebricks

---

README.md
frontend/.bowerrc
frontend/.gitignore
frontend/app/app.js
frontend/app/app.spec.js
frontend/app/index.html
frontend/app/view/index_page.view.html
frontend/bower.json
frontend/karma.conf.js
frontend/package.json

Added basic frontend skeleton with single index page.
Fixes #4

bank: added frontend skeleton

---

pom.xml

The bank application can be bundled into executable jar.
Fixes #7

bank/build: package bank into executable jar

---

frontend/app/app.js
frontend/app/app.test.js
frontend/app/index.html
frontend/app/view/index_page.view.html
frontend/app/view/transaction_history_page.view.html
frontend/express.js
frontend/package.json

Stubbed the backend so that we could isolate the frontend from it. Now we have an easy way for testing the UI. Also included the html5Mode in angular and Express from nodejs for the server, thus removing the fragment identifier -> "#" .
Fixes #6

frontend: stubbed backend

---

frontend/app/app.js
frontend/app/app.spec.js

Added 2 tests that verify that TransactionsHistoryCtrl is loading transactions when controller is created.

frontend: add tests for TransactionsHistoryCtrl

---

src/test/java/com/clouway/adapter/sitebricks/SitebricksMatchers.java

Added a sitebricks matcher that will help us test the Reply. There are two methods isOk() to check the status code and isSame(Reply<?> reply) to check the entity value.

bank: sitebricks reply matcher

---

pom.xml
src/main/java/com/clouway/core/Transaction.java
src/main/java/com/clouway/services/TransactionHistoryService.java
src/test/java/com/clouway/adapter/builder/JsonBuilder.java
src/test/java/com/clouway/adapter/sitebricks/SitebricksMatchers.java
src/test/java/com/clouway/bank/TransactionHistoryServiceTest.java

Added in memory implementation for the backend of the transaction history page.
Also implemented matcher that check the reply json value.
Fixes #26

bank: transaction history

---

frontend/app/app.js
frontend/app/index.html
frontend/webpack.config.js

Added a webpack development server with hot swap and inline option available. Also included the watch option for the webpack. Now we only refresh the page to see our changes, we won't have to start the server or bundle over and over again.

frontend: webpack dev server with hot swap

---

frontend/app/app.js
frontend/app/app.spec.js
frontend/app/view/index_page.view.html
pom.xml
src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/Jetty.java
src/main/java/com/clouway/bank/adapter/http/HomePageService.java
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentAccountRepository.java
src/main/java/com/clouway/bank/core/Account.java
src/main/java/com/clouway/bank/core/AccountRepository.java
src/main/java/com/clouway/bank/core/User.java
src/main/java/com/clouway/bank/core/UserSecurity.java
src/main/resources/com/clouway/bank/MainPage.html
src/test/java/com/clouway/bank/adapter/http/FakeRequest.java
src/test/java/com/clouway/bank/adapter/http/HomePageServiceTest.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java
src/test/java/com/clouway/bank/adapter/persistence/DatastoreRule.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentAccountRepositoryTest.java
src/test/java/com/clouway/bank/matchers/SitebricksMatchers.java

Deposit and withdraw functionality implemented. Database with frontend app.
Fixes #13

bank: execute simple bank operations

---

frontend/app/app.js
frontend/app/app.spec.js
frontend/app/view/index_page.view.html
frontend/package.json
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java

Corner cases for deposit and withdraw handled.
> Fixes #32

frontend: Show messages on executing operation

---

frontend/app/app.css
frontend/package.json
frontend/webpack.config.js
src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/adapter/http/HomePageService.java
src/main/java/com/clouway/bank/adapter/http/LoginPage.java
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/main/java/com/clouway/bank/adapter/http/SecurityFilter.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentSessionRepository.java
src/main/java/com/clouway/bank/core/Session.java
src/main/java/com/clouway/bank/core/SessionRepository.java
src/main/java/com/clouway/bank/core/User.java
src/main/java/com/clouway/bank/core/UserAuthentication.java
src/main/resources/com/clouway/bank/adapter/http/LoginPage.html
src/test/java/com/clouway/bank/adapter/http/FakeHttpServletRequest.java
src/test/java/com/clouway/bank/adapter/http/FakeHttpServletResponse.java
src/test/java/com/clouway/bank/adapter/http/FakeRequest.java
src/test/java/com/clouway/bank/adapter/http/HomePageServiceTest.java
src/test/java/com/clouway/bank/adapter/http/LoginPageTest.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java
src/test/java/com/clouway/bank/adapter/http/SecurityFilterTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentAccountRepositoryTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentSessionsRepositoryTest.java
src/test/java/com/clouway/bank/matchers/DatastoreRule.java

User login with username and password.
> Fixes #12

bank: easily sign up of a new user

---

frontend/app/app.js
frontend/app/app.spec.js
frontend/app/app.test.js
frontend/app/view/transaction_history_page.view.html
src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/main/java/com/clouway/bank/adapter/http/TransactionHistoryService.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentAccountRepository.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentTransactionRepository.java
src/main/java/com/clouway/bank/core/Account.java
src/main/java/com/clouway/bank/core/AccountRepository.java
src/main/java/com/clouway/bank/core/Transaction.java
src/main/java/com/clouway/bank/core/TransactionRecord.java
src/main/java/com/clouway/bank/core/TransactionRepository.java
src/test/java/com/clouway/bank/adapter/http/HomePageServiceTest.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java
src/test/java/com/clouway/bank/adapter/http/TransactionHistoryServiceTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentAccountRepositoryTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentTransactionRepositoryTest.java

Added DAO for the transaction history, now every transaction that is made by the users will be registered in the database and later be presented by the frontend to the user by his request. Thus, every user is now able to see his(and only his) transactions in page like view.
Fixes #10

bank: list transaction history of the account

---

frontend/app/app.js
src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/Jetty.java
src/main/java/com/clouway/bank/adapter/http/HomePageService.java
src/main/java/com/clouway/bank/adapter/http/LoginPage.java
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/main/java/com/clouway/bank/adapter/http/RegisterPage.java
src/main/java/com/clouway/bank/adapter/http/SecurityFilter.java
src/main/java/com/clouway/bank/adapter/http/TransactionHistoryService.java
src/main/java/com/clouway/bank/adapter/http/UserSecurityImpl.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentAccountRepository.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentSessionRepository.java
src/main/java/com/clouway/bank/core/AccountRepository.java
src/main/java/com/clouway/bank/core/Session.java
src/main/java/com/clouway/bank/core/SessionRepository.java
src/main/java/com/clouway/bank/core/User.java
src/main/java/com/clouway/bank/core/UserRepository.java
src/main/java/com/clouway/bank/core/UserSecurity.java
src/main/resources/com/clouway/bank/adapter/http/RegisterPage.html
src/test/java/com/clouway/bank/adapter/http/HomePageServiceTest.java
src/test/java/com/clouway/bank/adapter/http/LoginPageTest.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java
src/test/java/com/clouway/bank/adapter/http/SecurityFilterTest.java
src/test/java/com/clouway/bank/adapter/http/TransactionHistoryServiceTest.java
src/test/java/com/clouway/bank/adapter/http/UserSecurityImplTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentAccountRepositoryTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentSessionsRepositoryTest.java
src/test/java/com/clouway/bank/matchers/SitebricksMatchers.java

Users are able to register new account. Account is saved to db.
> Fixes #9
> Fixes #39

bank: registration of account

---

README.md

Added information about the version of Java, NodeJS and NPM on which the project is tested and working.

bank: updated README.md

---

frontend/app/app.js
frontend/app/app.spec.js
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/adapter/http/LogoutService.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentSessionRepository.java
src/main/java/com/clouway/bank/core/SessionRepository.java
src/main/resources/com/clouway/bank/MainPage.html
src/test/java/com/clouway/bank/adapter/http/LogoutServiceTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentSessionsRepositoryTest.java

Added user logout, so that users have the ability to terminate their sessions at will, for obvious security reasons.
Fixes #43

bank: added user logout

---

frontend/app/app.js
frontend/app/app.test.js
frontend/app/index.html
frontend/index.dev.js
frontend/package.json
frontend/webpack.config.js
src/main/resources/com/clouway/bank/MainPage.html

Fixed development environment to work as expected and an example interceptor is added in app.js which redirects to /login page after server replies with 401.

frontend: fix development build to work as expected

---

bundle.sh
frontend/app/app.js
src/main/java/com/clouway/bank/adapter/http/SecurityFilter.java
src/main/java/com/clouway/bank/adapter/http/TransactionHistoryService.java
src/test/java/com/clouway/bank/adapter/http/FakeHttpServletResponse.java
src/test/java/com/clouway/bank/adapter/http/FakeRequest.java
src/test/java/com/clouway/bank/adapter/http/SecurityFilterTest.java

On invalid session or missing valid cookie, the user is redirected to "/login"
`fixes #47`

bank: redirect to login

---

src/main/java/com/clouway/bank/BankBootstrap.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentSessionRepository.java
src/main/java/com/clouway/bank/core/SessionCleaner.java
src/main/java/com/clouway/bank/core/SessionsCleaner.java
src/test/java/com/clouway/bank/core/SessionCleanerTest.java

Expired sessions are removed from bd every 5 minutes.
> Fixes #50

bank: cleaning expired sessions

---

frontend/app/app.js
frontend/app/app.spec.js
frontend/app/app.test.js
frontend/app/index.html
frontend/app/view/password_change_page.view.html
src/main/java/com/clouway/bank/BankModule.java
src/main/java/com/clouway/bank/adapter/http/UserPasswordChangingService.java
src/main/java/com/clouway/bank/adapter/persistence/PersistentAccountRepository.java
src/main/java/com/clouway/bank/core/AccountRepository.java
src/main/resources/com/clouway/bank/MainPage.html
src/test/java/com/clouway/bank/adapter/http/UserPasswordChangingServiceTest.java
src/test/java/com/clouway/bank/adapter/persistence/PersistentAccountRepositoryTest.java

Added password change functionality for the users, now they can change their password at will. This will improve their security!
Fixes #53

bank: added user password change

---

src/main/java/com/clouway/bank/adapter/http/HomePageService.java
src/main/java/com/clouway/bank/adapter/http/LogoutService.java
src/main/java/com/clouway/bank/adapter/http/OperationsService.java
src/main/java/com/clouway/bank/adapter/http/SecurityFilter.java
src/main/java/com/clouway/bank/adapter/http/TransactionHistoryService.java
src/main/java/com/clouway/bank/adapter/http/UserPasswordChangingService.java
src/main/java/com/clouway/bank/adapter/http/UserSecurityImpl.java
src/main/java/com/clouway/bank/core/UserNotAuthorizedException.java
src/main/java/com/clouway/bank/core/UserSecurity.java
src/test/java/com/clouway/bank/adapter/http/HomePageServiceTest.java
src/test/java/com/clouway/bank/adapter/http/LogoutServiceTest.java
src/test/java/com/clouway/bank/adapter/http/OperationsServiceTest.java
src/test/java/com/clouway/bank/adapter/http/SecurityFilterTest.java
src/test/java/com/clouway/bank/adapter/http/TransactionHistoryServiceTest.java
src/test/java/com/clouway/bank/adapter/http/UserPasswordChangingServiceTest.java
src/test/java/com/clouway/bank/adapter/http/UserSecurityImplTest.java

The mothod getCurrent() no longer returns Optional. Instead it will throw exception which is catched at the SecurityFilter, then unauthorised respond is returned by the server.

bank: fix on getCurrent() method
